# Generated by Django 2.1.7 on 2019-04-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image1',
            field=models.ImageField(default='defhotel.jpg', upload_to='hotel_pics'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(default='defhotel.jpg', upload_to='hotel_pics'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(default='defhotel.jpg', upload_to='hotel_pics'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image4',
            field=models.ImageField(default='defhotel.jpg', upload_to='hotel_pics'),
        ),
    ]
