# Generated by Django 2.1.7 on 2019-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20190414_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lng',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
    ]
