# Generated by Django 2.1.7 on 2019-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190414_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
