# Generated by Django 2.1.7 on 2019-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
