# Generated by Django 2.1.7 on 2019-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defprofile.jpg', upload_to='profile_pics'),
        ),
    ]
