# Generated by Django 2.1.7 on 2019-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
