# Generated by Django 2.1.7 on 2019-03-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190325_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
